### PR TITLE
Fix browser build sync and alive behavior

### PR DESCRIPTION
**Pull request by dnzxy**
This PR addresses issue LoopKit/Loop#2192.  It attempts to fix browser build failures many users have come across with browser build attempting to sync the forker's `alive` branch and running into merge conflicts. This is due to `alive` being created from `refs/head/dev` of LoopWorkspace, not `main` when trying to sync changes for a user that wants to build `main`.

A typical failure we've currently come across (cf. LoopKit/Loop#2192) is a failure in the `Check upstream and keep alive` steo of the `build_loop.yaml` action that looks as follows 👇 
image

This PR proposes a solution by detecting whether the build action is run for `main` or `dev` and providing two  branches (`alive-main` and `alive-dev`) and use the correct one.

- Added logic to extend the alive check for the existence of either `alive-main` or `alive-dev` branches.
  - Resolved an issue where unexpected successes were occurring when failures were expected.
  - Implemented a check to determine the existence of the `alive-main` and `alive-dev` branches and create them if they do not exist.
- Introduced a mechanism to identify the current branch being run (either `main` or `dev`).
  - Based on the current branch, the corresponding alive branch (`alive-main` or `alive-dev`) will be used to check for upstream changes.
- Set a new variable `ABORT_SYNC` to `true` when the current branch is neither `dev` nor `main`.
  - The syncing attempt will proceed based on the `ABORT_SYNC` variable status.

- This PR also updates the links for validation errors to show the correct AppStoreConnect in the solution hints

- Ensured proper branch synchronization to prevent build inconsistencies and failures.

### CODE REVIEW

**Comment by marionbarker** [comment]
## Summary
To enable testing for the automatic sync and build requires some configuration adjustments.
I have some logs for @dnzxy to review.
I think it is not working - but maybe I messed something up in my configuration.

## Configuration:
* commit build_loop.yml file from this PR into main branch and dev branch in my personal LoopWorkspace fork [marionbarker](https://github.com/marionbarker/LoopWorkspace)
* Add an additional update (for testing only) to look at marionbarker instead of LoopKit as the upstream repo
   * This will allow me to add commits to marionbarker to test the sync part of this PR
* Use my GitHub Org (loopdocs-tester) for testing
   * Delete the LoopWorkspace fork from loopdocs-tester
   * Fork a new LoopWorkspce from marionbarker instead of LoopKit

**Important**
The tests must use branch names `main` and `dev`. Any other branch names skip some of the steps.
The other edit enables me to test with marionbarker where I can add commits as desired to trigger updates.
After the first 3 minutes, the job is into the build portion, so can cancel the job to save time and still get the logs.

## Tests

### Test One - new Looper who just created a fork
* The loopdocs-tester org already has all the secrets configured to build using my developer ID
* Build Loop (main) [Successful log]()
   * Initially, the only branch was `main`
   * Note that these branches were created: `alive-dev` and `alive-main`

### Test Two - create a new branch name (main-with-new-name)
* Build Loop (main-with-new-name) [Cancelled log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9968691491)

### Test Three - modify main branch at marionbarker, should sync as part of build
* Build Loop (main) [Cancelled log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9968910801)
* no indication in log of a sync and the repo shows as 1 commit behind main

**Comment by dnzxy** [comment]
Test One looks good.

Test Two looks good. It just skips any syncing (see [here](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9968691491/job/27544383339) and [here](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9968691491/job/27544386651)) but attempts to build just fine; if not cancelled this build should've succeeded.

Test Three is indeed faulty; I've identified the bug. The check condition is faulty. 
Since the check condition is faulty here:

```yaml
if: | # do not run the upstream sync action on the upstream repository
        needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' &&
        vars.SCHEDULED_SYNC != 'false' && github.repository_owner != 'marionbarker' && steps.check_branch.outputs.on_main == 'true'
```
The condition `steps.check_branch.outputs.on_main == 'true'` needs to be `steps.check_branch.outputs.ABORT_SYNC == 'true'`. That is an oversight on my part, apologies. I will push a fix later tonight my time

**Comment by dnzxy** [comment]
Found two additional issues that have been fixed now. 
I have also updated the AppStoreConnect URL that is displayed for validation error hints to the new one.

**Comment by marionbarker** [comment]
## Summary
Success for manual tests
Configure an automatic run to happen overnight

## Configuration
* Use marionbarker/LoopWorkspace as `UPSTREAM_REPO` so I can control commits
* Use loopdocs-tester with a fork from LoopWorkspace
* work with @dnzxy via PM to get to the point where we think all the cases are handled.
   * ignore all the extra commits to marionbarker:main; that was early testing

## Preparation
* Use the build_loop.yml file from dnzxy:fix-sync-alive, commit `b49415e`
* commit that version into `main` for marionbarker
* edit the UPSTREAM from LoopKit to marionbarker in build_loop.yml and commit
* push those changes to `main` and replicate in `dev` for marionbarker
* a number of preliminary tests are seen in the logs at https://github.com/loopdocs-tester/LoopWorkspace/actions
* these were interrupted to save time while updating the code. The last 2 interrupted test were successful
* repeat those test and allow build to finish so we get a green check.

## Test 1:
* main: status loopdocs-tester is up to date with marionbarker
* delete alive branches, manual run of build
* success: alive-dev and alive-main are created, build without errors [log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9985548326)

## Test 2:
* main: marionbarker, modify the cron line
   * this updates the commit and modifies when the automatic sync and build happen
   * adjust the monthly build date to 18th (which means 11 pm tonight my local time)
* main: observe loopdocs-tester is 1 commit behind marionbarker
* delete alive branches, manual run of build
* success: alive-dev and alive-main are created
* observe main: status loopdocs-tester is up to date with marionbarker
* I assume build will success - it will be next log

## Test 3:
* main: marionbarker add extra line to fastlane/testflight.md to update commit
* main: observe loopdocs-tester is 1 commit behind marionbarker
* the automatic build should occur in about an hour - check in the morning that it did automatically run with and automatic update

**Comment by marionbarker** [comment]
## Summary
Check the log files.
As expected, both Test 2 and Test 3 were successful.
A few more tests are planned.
When those are done, I will indicate that testing is completed.

## Recap of Tests 2 and 3
* Test 2 was a manual test where the fork was behind in commits and no alive branches existed
   * Successful manual build of main [log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9985684621)
* Test 3 was an automatic build test where the fork was behind in commits, it launched as scheduled and was successful
   * Successful scheduled build of main [log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9986524170)

**Comment by marionbarker** [comment]
## Summary
* Next Test is configured - come back with a new comment after allowing time for the scheduled sync and build test to run

## Additional Tests
* Continue numbering from my previous 2 comments

### Test 4: auto-sync test with `main` as default branch
* main: marionbarker modify cron to check for updates every day at 1600 UTC (9 am local)
* manually update `loopdocs-tester:main` to be up to date with marionbarker
* main: marionbarker add extra line to fastlane/testflight.md to update commit
* main: observe loopdocs-tester is 1 commit behind marionbarker
* wait for scheduled update to happen

**Comment by marionbarker** [comment]
## Summary
* Test 4 (auto-sync with `main` as default branch succeeded)
* Test 5 succeeded and Test 6 prepared

### Test 4 result
* scheduled sync and build succeeded for main: [log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9995099898)

### Test 5: add `dev` branch and do a manual build
* add dev branch to loopdocs-tester from marionbarker
* dev: observe loopdocs-tester is up to date
* dev: build with dev selected (main is still default)
* Successful manual build of dev: [log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9996504948)

### Test 6: make `dev` branch default and test auto-sync
* dev: marionbarker modify cron to check for updates every day at 1900 UTC
* manually update `loopdocs-tester:dev` to be up to date with marionbarker
* dev: marionbarker add extra line to fastlane/testflight.md to update a commit
* dev: loopdocs-tester: observe 1 commit behind
* dev: loopdocs-tester: set as default branch
* wait for scheduled update to happen

**Comment by marionbarker** [comment]
## Summary
* Test 6 - success
* Test 7 - started
* Test 8 and 9 (sync and build tests configured)

### Test 6 result
* success: dev branch as default, scheduled sync and build was successful
* [log](https://github.com/loopdocs-tester/LoopWorkspace/actions/runs/9997284885)

### Test 7: branch that is not main or dev
* create branch other-branch from dev in loopdocs-tester
* manually build and demonstrate this succeeds without trying to update

### Configure for Test 8 and 9
* dev: marionbarker, modify the cron lines
   * adjust the weekly sync check every day at 20:00 or 1 pm local
   * adjust the monthly build date to 19th at 21:00 or 2 pm local (today)
* manually adjust dev for loopdocs-tester to be up to date with marionbarker

### Test 8: scheduled sync with no updates needed
* expect this to succeed with very fast action - no update needed, so does not build.

### Test 9: scheduled build with no updates needed
* expect this to succeed and build - no update needed, but cron says it's time for the monthly build

**Comment by marionbarker** [comment]
## Update Summary
* The portion of build_loop.yml that affects the browser build sync and alive behavior has not changed so previous tests are valid
* However, I will update main and dev again in marionbarker to match the latest version of fix-sync-alive

## Previous Test Summary
The automated tests from my previous comment:
* Test 8 was not configured properly (the alive-dev was behind the upstream dev)
   * Scheduled sync ran and built for this reason, successful build
* Test 9 did not run because I made a mistake in the cron

## Configuration - Part 1
* In marionbarker main, checkout .github/workflows/*.yml from dnzxy:fix-sync-alive and commit
* in marionbarker dev, repeat the process
* in marionbarker main, edit the UPSTREAM repository to marionbarker and commit
* in marionbarker dev, cherry-pick last main commit
* verify that `git diff main dev --  .github/workflows/*.yml` is empty

## Test 8 and 9 - prepare to repeat
* adjust cron for dev to this:
   * Test 8 should run at 19:00 local, 02:00 UTC tomorrow
   * Test 9 should run at 20:00 local, 03:00 UTC on the 19th
* This time manually update loopdocs-tester dev to be up to date with marionbarker && delete the alive-branches 
* Expected behavior
   * Test 8 should detect no new commits and skip the build
   * Test 9 should detect no new commits and build

**Comment by marionbarker** [comment]
Test 8 was a Success. (Build 25 scheduled - no new commits and skipped the build).

Test 9 was still not configured correctly - you have to change the cron in 2 places to get a scheduled build when there are no new commits.
* Test 9 should run at 06:00 UTC (or 11 pm local)

**Comment by marionbarker** [comment]
### Results

Test 9 - finally succeeded (or I should say, I finally succeeded at properly configuring the cron job)
* build loop 27 - there were no commits to trigger a build, but the cron line for scheduled building matched the cron line for doing a scheduled build and a new build happened and succeeded.

Test 8 - accidental repeat
* build loop 28 - cron job triggered a check for commits, there were none, so build was skipped

### Prepare for next test

Configure for Test 10
* modify the environment variables for the loopdocs-tester LoopWorkspace to set SCHEDULED_SYNC to false
* update the cron to 
   * restore original values for scheduled build
   * modify line for scheduled sync to 14:00 everyday (or at 7 am local)
* commit changes and sync loopdocs-tester
* modify testflight.md so there will be a commit difference
* observe the loopdocs-tester is one commit behind marionbarker
* expected behavior - scheduled action will note there are new commits but because SCHEDULED_SYNC is false, it will skip both the sync and the build

**Comment by marionbarker** [comment]
## Summary:
All tests were successful.
**These changes should be merged into LoopWorkspace main and dev ASAP**

### Results:
Test 10 was successful, build 29 scheduled.
* because SCHEDULED_SYNC was false, only keep alive was run and build was skipped

**Pull request merged**
