### PR TITLE
Main 3.2.2 custom monica libre3

### PR DESCRIPTION
**Pull request by myanezpagans**

### CODE REVIEW

**Comment by marionbarker** [comment]
@myanezpagans Please close this. Do not create pull requests to LoopKit. They need to be to your own repository.
* https://loopkit.github.io/loopdocs/gh-actions/gh-customize/#do-not-make-a-pull-request-to-original-copy

**Comment by myanezpagans** [comment]
Dear Marion,

Many thanks for your email. I am really sorry but I am afraid I do not know
how to close this. If you could please guide me on how to get this done, I
can  certainly try to get this implemented. Just please do not close or
block my loop account as I depend heavily on this for my insulin needs. I
am not very digital savvy and setting up loop has been a huge challenge for
me.

Many thanks and all the best,

Monica

**Comment by marionbarker** [comment]
@myanezpagans 

Monica: 

First some explanation, then instructions on how to close the pull request (PR).
* Because you opened this pull request, you can close it. Otherwise, one of the developers who has permission can close it, but it does take them time - so it is polite for you to close it. (I do not have permission.)
* The act of closing the pull request simply removes it from the "open" list and makes it easier to see "real" pull requests that should be considered.
* Closing the PR has no effect on your copy of Loop or any of your builds. Furthermore, it just moves the PR from the "open" to "closed" category, it doesn't delete it.

Instructions to close:
* click on this link to open the PR: https://github.com/LoopKit/LoopWorkspace/pull/95
* scroll down near the bottom where you see the **Add a comment** box
* below that is a button that says **Close pull request**
* tap on the **Close pull request** and confirm

**Comment by myanezpagans** [comment]
Many thanks, Marion. I have followed your instructions and I think the pull
request is now closed. Grateful if you could please confirm this to me.

Many thanks again for your help with this and happy holidays!l

Monica

**Comment by marionbarker** [comment]
That worked. Thank you.

**Pull request closed without merging**
