### PR TITLE
Update LoopConfigOverride.xcconfig

### PR DESCRIPTION
**Pull request by gpayen69**
Added carbs reading from Apple Health.

### CODE REVIEW

**Comment by marionbarker** [comment]
It looks like the changes are a personal customizations rather than updates intended for the wider Loop community. 

This is a common occurrence, so no worries! But please close this PR.

**Closing the pull request alleviates some of the workload on the project's maintainers, who review and manage these contributions.**

BR/Marion

**Comment by gpayen69** [comment]
Hello, Yes it was a mistake when creating a branche. I did close that request. BRGuillaume Le 12 oct. 2024 à 19:20, Marion Barker ***@***.***> a écrit :﻿
It looks like the changes are a personal customizations rather than updates intended for the wider Loop community.
This is a common occurrence, so no worries! But please close this PR.
Closing the pull request alleviates some of the workload on the project's maintainers, who review and manage these contributions.
BR/Marion

**Comment by marionbarker** [comment]
The request is still open. Please try again to close it - you need to be logged into github.

**Comment by gpayen69** [comment]
Marion, Well, on my side it is closed. May be I have some additional stuff to do ? BR GuillaumeLe 16 oct. 2024 à 16:33, Marion Barker ***@***.***> a écrit :﻿
The request is still open. Please try again to close it - you need to be logged into github.

**Comment by marionbarker** [comment]
Please go to this link: https://github.com/LoopKit/LoopWorkspace/pull/206
Scroll to the bottom and tap Close.

Included below is a graphic from LoopDocs:

Screenshot 2024-10-16 at 9 49 25 AM

**Comment by gpayen69** [comment]
Should be closed now !?

**Pull request closed without merging**
