### PR TITLE
Added MixpanelService to Loop

### PR DESCRIPTION
**Pull request by Camji55**

### CODE REVIEW

**Review by ps2 — COMMENTED** [review]
Thanks! I think the submodule needs to be updated to point to main/HEAD, and I am wondering why there is a guard here: https://github.com/LoopKit/MixpanelService/blob/main/MixpanelServiceKit/MixpanelService.swift#L67-L69; many of Loop events do not have properties associated with them.

**Comment by Camji55** [comment]
@ps2 I will look into this, thank you!

**Comment by Camji55** [comment]
@ps2 the additional `identify` method has been added.

**Comment by ps2** [comment]
I'm more waiting on the guard mentioned above, as it seems like it's not recording most of the events, since they don't have properties.

**Comment by Camji55** [comment]
> I'm more waiting on the guard mentioned above, as it seems like it's not recording most of the events, since they don't have properties.

@ps2 okay, this is done!

**Comment by ps2** [comment]
Thanks!

**Pull request merged**
